[package]
name = "aoc-autobuild"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[dependencies]
{CRATE_NAME} = { path = "../../.." }
aoc-runner = { path = "../../../../aoc-runner" }