[package]
name = "aoc-runner-derive"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.18", features = ["extra-traits"] }
quote = "0.6.9"

[features]
default = ["syn/full"]
