[package]
name = "aoc-runner-derive"
version = "0.1.0"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.19", features = ["extra-traits"] }
quote = "0.6.10"
proc-macro2 = "0.4.21"
aoc-runner-internal = { path = "../aoc-runner-internal" }

[features]
default = ["syn/full"]
